import React, { Fragment } from "react";
import Box from "./Box";

export default function BoxCont() {
  return (
    <Fragment>
      <Box
        image="/dashboard/images/pdf.svg"
        type="my-file.pdf"
        name="Elzero"
        date="20/06/2020"
        size="5.5"
      />
      <Box
        image="/dashboard/images/avi.svg"
        type="my-file.avi"
        name="Admin"
        date="16/5/2021"
        size="12.5MB"
      />
      <Box
        image="/dashboard/images/eps.svg"
        type="my-file.eps"
        name="Uploader"
        date="16/5/2021"
        size="2.7MB"
      />
      <Box
        image="/dashboard/images/pdf.svg"
        type="my-file.psd"
        name="Osama"
        date="16/5/2021"
        size="15.1MB"
      />
      <Box
        image="/dashboard/images/dll.svg"
        type="my-file.dll"
        name="Coder"
        date="16/5/2021"
        size="2.2MB"
      />
      <Box
        image="/dashboard/images/png.svg"
        type="my-file.png"
        name="Designer"
        date="16/5/2021"
        size="1.1MB"
      />
      <Box
        image="/dashboard/images/dll.svg"
        type="my-file.dll"
        name="Coder"
        date="16/5/2021"
        size="2.2MB"
      />
      <Box
        image="/dashboard/images/png.svg"
        type="my-file.png"
        name="Designer"
        date="16/5/2021"
        size="1.1MB"
      />
      <Box
        image="/dashboard/images/dll.svg"
        type="my-file.dll"
        name="Coder"
        date="16/5/2021"
        size="2.2MB"
      />
      <Box
        image="/dashboard/images/avi.svg"
        type="my-file.avi"
        name="Admin"
        date="16/5/2021"
        size="12.5MB"
      />
      <Box
        image="/dashboard/images/eps.svg"
        type="my-file.eps"
        name="Uploader"
        date="16/5/2021"
        size="2.7MB"
      />
      <Box
        image="/dashboard/images/pdf.svg"
        type="my-file.psd"
        name="Osama"
        date="16/5/2021"
        size="15.1MB"
      />
      <Box
        image="/dashboard/images/pdf.svg"
        type="my-file.pdf"
        name="Elzero"
        date="20/06/2020"
        size="5.5"
      />
      <Box
        image="/dashboard/images/avi.svg"
        type="my-file.avi"
        name="Admin"
        date="16/5/2021"
        size="12.5MB"
      />
      <Box
        image="/dashboard/images/pdf.svg"
        type="my-file.pdf"
        name="Elzero"
        date="20/06/2020"
        size="5.5"
      />
      <Box
        image="/dashboard/images/avi.svg"
        type="my-file.avi"
        name="Admin"
        date="16/5/2021"
        size="12.5MB"
      />
      <Box
        image="/dashboard/images/eps.svg"
        type="my-file.eps"
        name="Uploader"
        date="16/5/2021"
        size="2.7MB"
      />
      <Box
        image="/dashboard/images/pdf.svg"
        type="my-file.psd"
        name="Osama"
        date="16/5/2021"
        size="15.1MB"
      />
      <Box
        image="/dashboard/images/dll.svg"
        type="my-file.dll"
        name="Coder"
        date="16/5/2021"
        size="2.2MB"
      />
      <Box
        image="/dashboard/images/png.svg"
        type="my-file.png"
        name="Designer"
        date="16/5/2021"
        size="1.1MB"
      />
      <Box
        image="/dashboard/images/dll.svg"
        type="my-file.dll"
        name="Coder"
        date="16/5/2021"
        size="2.2MB"
      />
      <Box
        image="/dashboard/images/png.svg"
        type="my-file.png"
        name="Designer"
        date="16/5/2021"
        size="1.1MB"
      />
      <Box
        image="/dashboard/images/dll.svg"
        type="my-file.dll"
        name="Coder"
        date="16/5/2021"
        size="2.2MB"
      />
      <Box
        image="/dashboard/images/avi.svg"
        type="my-file.avi"
        name="Admin"
        date="16/5/2021"
        size="12.5MB"
      />
      <Box
        image="/dashboard/images/eps.svg"
        type="my-file.eps"
        name="Uploader"
        date="16/5/2021"
        size="2.7MB"
      />
      <Box
        image="/dashboard/images/pdf.svg"
        type="my-file.psd"
        name="Osama"
        date="16/5/2021"
        size="15.1MB"
      />
      <Box
        image="/dashboard/images/pdf.svg"
        type="my-file.pdf"
        name="Elzero"
        date="20/06/2020"
        size="5.5"
      />
      <Box
        image="/dashboard/images/avi.svg"
        type="my-file.avi"
        name="Admin"
        date="16/5/2021"
        size="12.5MB"
      />
    </Fragment>
  );
}
